# Generated by Django 2.2.5 on 2019-09-09 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_auto_20190909_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='date_applied',
        ),
    ]
