# Generated by Django 2.2.5 on 2019-09-12 00:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_auto_20190910_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='application_status',
        ),
        migrations.RemoveField(
            model_name='application',
            name='company_contact_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='company_contact_phone',
        ),
        migrations.AlterField(
            model_name='application',
            name='date_applied',
            field=models.DateField(blank=True, default=datetime.date(2019, 9, 12)),
        ),
    ]
