# Generated by Django 2.2.5 on 2019-09-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_auto_20190914_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='string_id',
            field=models.CharField(default='application_id', max_length=100),
        ),
    ]
