# Generated by Django 2.2.5 on 2019-09-14 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_remove_application_application_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='string_id',
        ),
    ]
