# Generated by Django 2.2.5 on 2019-09-16 22:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_remove_application_string_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='date_applied',
            field=models.DateField(blank=True, default=datetime.date(2019, 9, 16)),
        ),
    ]
